# Config file for the build system
# Project root is automatically inferred

[paths]
bin_dir = bin
obj_dir = bin-int
premake_exec = premake/premake5
premake_file = premake5.lua
premake_dir = premake

[build]
generator = gmake
configuration = Debug
verbose = false
dev = true

[project]
exec_name = IgnisEditor

[setup]
premake_version = 5.0.0-beta8

[plugins]
plugin_dir = premake/plugins

[plugin.export-compile-commands]
url = https://github.com/tarruda/premake-export-compile-commands
type = premake